package com.mycompany.simclavier;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ntessier
 */
public class Clavier extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public Clavier() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMess = new javax.swing.JTextField();
        fondClavier = new java.awt.Panel();
        Touche0 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clavier");
        setPreferredSize(new java.awt.Dimension(220, 250));
        getContentPane().setLayout(null);

        textMess.setEditable(false);
        textMess.setForeground(new java.awt.Color(0, 0, 0));
        textMess.setToolTipText("");
        getContentPane().add(textMess);
        textMess.setBounds(30, 30, 90, 28);

        fondClavier.setBackground(new java.awt.Color(0, 0, 0));
        fondClavier.setPreferredSize(new java.awt.Dimension(120, 160));
        fondClavier.setLayout(new java.awt.GridLayout(4, 3, 1, 1));

        Touche0.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        Touche0.setText("0");
        Touche0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        Touche0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Touche0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Touche0.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(Touche0);

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton2.setText("1");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.setPreferredSize(new java.awt.Dimension(26, 26));
        jButton2.setRequestFocusEnabled(false);
        fondClavier.add(jButton2);

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton3.setText("2");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton3);

        jButton9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton9.setText("3");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton9.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton9);

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton5.setText("4");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton5.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton5);

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton4.setText("5");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton4);

        jButton6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton6);

        jButton7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton7.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton7);

        jButton8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton8.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton8);

        jButton10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton10.setText("9");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton10.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton10);

        jButton11.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton11.setText("*");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton11.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton11);

        jButton12.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jButton12.setText("#");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 20)));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton12.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton12);

        getContentPane().add(fondClavier);
        fondClavier.setBounds(40, 90, 140, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clavier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Touche0;
    private java.awt.Panel fondClavier;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField textMess;
    // End of variables declaration//GEN-END:variables
}
